name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test D2 plugin
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: d2 --version
